project_name: 'road_segment'
image_dir: 'data/Images'
train_filepath: 'data/Train.csv'
test_filepath: 'data/Test.csv'
checkpoint_dir: 'checkpoints'
submission_dir: 'submissions'
arch: 'resnet18'
test_size: 0.2
batch_size: 32
device: 'cuda'
num_epochs: 48
lr: 0.001
lr_scheduler:
  step_size: 10
  gamma: 0.2
