project_name: 'road_segment_folds_lr_scheduler_eff_b1'
image_dir: 'data/Images'
train_filepath: 'data/Train.csv'
test_filepath: 'data/Test.csv'
checkpoint_dir: 'checkpoints_folds'
submission_dir: 'submissions_folds'
arch: 'efficientnet-b2' #
num_splits: 5
batch_size: 20
device: 'cuda'
num_epochs: 24
lr: 0.001
ensemble_mode: 'geom' # geom
lr_scheduler:
  step_size: 10
  gamma: 0.1
