project_name: 'road_segment'
image_dir: 'data/Images'
train_filepath: 'data/Train.csv'
test_filepath: 'data/Test.csv'
checkpoint_dir: 'checkpoints'
submission_dir: 'submissions'
arch: 'resnet18'
test_size: 0.2
batch_size: 4
device: 'cpu'
num_epochs: 8
lr: 0.01
lr_scheduler:
  step_size: 5
  gamma: 0.5
