project_name: 'road_segment_folds'
image_dir: 'data/Images'
train_filepath: 'data/Train.csv'
test_filepath: 'data/Test.csv'
checkpoint_dir: 'checkpoints_folds'
submission_dir: 'submissions_folds'
arch: 'efficientnet-b0' # resnet18
num_splits: 5
batch_size: 32
device: 'cuda'
num_epochs: 24
lr: 0.001
ensemble_mode: 'mean' # geom

